"use client";

import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'ru' | 'en';

type Translations = {
    [key in Language]: {
        [key: string]: string;
    };
};

const translations: Translations = {
    ru: {
        "nav.home": "Главная",
        "nav.services": "Услуги",
        "nav.modular": "Модульные",
        "nav.projects": "Проекты",
        "nav.about": "О компании",
        "nav.licenses": "Лицензии",
        "nav.contacts": "Контакты",
        "nav.consultation": "Получить консультацию",
        "button.back": "Назад",
        "hero.subtitle": "Казахстан",
        "hero.description": "Модульные и строительные проекты в Казахстане. Реализация сложных задач с инженерной точностью и стандартами качества.",
        "hero.request": "Запросить предложение",
        "hero.projects": "Смотреть проекты",
        "hero.trust.years": "13+ лет опыта",
        "hero.trust.projects": "60+ проектов",
        "hero.trust.license": "Лицензия 1 категории",

        "about.title": "Профиль компании",
        "about.desc": "RBI Engineering Group — строительная организация полного цикла, специализирующаяся на сложных строительно-монтажные работах и проектировании высокотехнологичных модульных сооружений.",
        "about.subdesc": "Мы реализуем индустриальные и инфраструктурные проекты по всему Казахстану, обеспечивая высокую культуру инжиниринга и соблюдение строгих технологических стандартов.",
        "about.stat.years": "ЛЕТ НА РЫНКЕ",
        "about.stat.projects": "РЕАЛИЗОВАННЫХ ОБЪЕКТОВ",
        "about.stat.employees": "СОТРУДНИКОВ",
        "about.stat.machinery": "ЕДИНИЦЫ ТЕХНИКИ",
        "about.stat.license": "ЛИЦЕНЗИЯ НА СМР",
        "about.stat.license.suffix": " КАТ.",

        "activities.eyebrow": "Услуги",
        "activities.title": "Комплексные инженерные решения",
        "activities.desc": "Обеспечиваем безупречное качество исполнения на каждом этапе проекта.",
        "activities.modular.title": "Модульные сооружения",
        "activities.modular.desc": "Оперативное возведение высокотехнологичных объектов «под ключ».",
        "activities.construction.title": "Строительно-монтажные работы",
        "activities.construction.desc": "Профессиональная реализация масштабных инфраструктурных и промышленных проектов.",
        "activities.networks.title": "Инженерные сети",
        "activities.networks.desc": "Проектирование и инсталляция сложных внутренних и внешних коммуникационных систем.",
        "activities.finishing.title": "Отделочные работы",
        "activities.finishing.desc": "Финальная отделка премиального уровня с использованием износостойких материалов.",
        "activities.planning.title": "Проектирование и планирование",
        "activities.planning.desc": "Разработка высокоточной проектной документации и генеральное планирование.",
        "activities.mounting.title": "Монтаж / демонтаж",
        "activities.mounting.desc": "Сложный монтаж технологического оборудования и металлоконструкций любого масштаба.",
        "activities.button": "Все услуги",

        "modular.title": "Модульные сооружения",
        "modular.text": "Модульные сооружения — это быстрый и практичный способ получить готовое помещение. Подходит для удалённых локаций и разных типов объектов.",
        "modular.subtitle": "Почему это выгодно?",
        "modular.detail": "Экономия времени и бюджета: здания собираются как конструктор прямо на объекте. Полная заводская готовность, включая отделку и инженерные системы.",
        "modular.benefit1.title": "Быстро",
        "modular.benefit1.desc": "Сборка за несколько дней",
        "modular.benefit2.title": "Надежно",
        "modular.benefit2.desc": "Работает в любых погодных условиях",
        "modular.benefit3.title": "Мобильно",
        "modular.benefit3.desc": "Легко перевезти на новое место",
        "modular.button": "Подробнее",

        "competencies.eyebrow": "Преимущества",
        "competencies.title": "Ключевые компетенции",
        "competencies.title_alt": "Почему выбирают нас",
        "competencies.c1.title": "Опыт и масштаб",
        "competencies.c1.desc": "13+ лет на рынке Казахстана, 60+ реализованных проектов.",
        "competencies.c2.title": "Профессиональная команда",
        "competencies.c2.desc": "50+ сотрудников, регулярная аттестация и повышение квалификации.",
        "competencies.c3.title": "Техническая база",
        "competencies.c3.desc": "Собственный парк 53+ единиц строительной техники и сервисная служба.",
        "competencies.c4.title": "Специализация на модулях",
        "competencies.c4.desc": "Знаем особенности модульных сооружений и комплектаций.",
        "competencies.c5.title": "Партнёрская сеть",
        "competencies.c5.desc": "Сотрудничество с крупными производителями и компаниями (DoorHan, Power China и др.).",
        "competencies.c6.title": "Документы и подтверждения",
        "competencies.c6.desc": "Лицензия 1 категории и 68+ рекомендательных писем.",

        "where.title": "Сферы применения",
        "where.i1": "Посты охраны / КПП",
        "where.i2": "Диспетчерские и технические помещения",
        "where.i3": "Заводы",
        "where.i4": "Ветровые электростанции",
        "where.i5": "Мобильные офисы и школы",
        "where.i6": "Военное строительство",
        "where.i7": "Жилые и медицинские объекты",

        "projects.title": "Проекты",
        "projects.desc": "Примеры выполненных работ по модульным решениям и монтажным проектам.",
        "projects.cat.modular": "Модульные сооружения",
        "projects.cat.metal": "Монтаж / металлоконструкции",
        "projects.p1.title": "ВЭС «Хромтау»",
        "projects.p1.label": "Партнеры",
        "projects.p2.title": "Монтаж ветровых генераторов",
        "projects.p2.label": "Локация",
        "projects.p2.value": "Петропавловск",
        "projects.p3.title": "Столовая для военной базы",
        "projects.p3.label": "Заказчик",
        "projects.p3.value": "АО «Əскери Құрылыс»",
        "projects.p4.title": "Монтаж конструкции ТРЦ «Хан Шатыр»",
        "projects.p4.label": "Объект",
        "projects.p4.value": "Хан Шатыр",
        "projects.p5.title": "Штаб строительства",
        "projects.p5.label": "Площадь",
        "projects.p5.value": "850 м²",
        "projects.p6.title": "Вахтовый поселок",
        "projects.p6.label": "Вместимость",
        "projects.p6.value": "300 чел",
        "projects.p_conf.title": "Конференц-зал (Алматы)",
        "projects.p_conf.label": "Локация",
        "projects.p_conf.value": "г. Алматы",
        "projects.p_lab.title": "Лаборатория ПЦР (Аксай)",
        "projects.p_lab.label": "Локация",
        "projects.p_lab.value": "г. Аксай",
        "projects.p_pavilion.title": "Остановочный павильон",
        "projects.p_pavilion.label": "Заказчик",
        "projects.p_pavilion.value": "Акимат города",
        "projects.p_terminal.title": "Таможенный терминал",
        "projects.p_terminal.label": "Тип",
        "projects.p_terminal.value": "Инфраструктурный объект",
        "projects.p_factory.title": "Заводы и складские помещения",
        "projects.p_factory.label": "Заказчик",
        "projects.p_factory.value": "ТОО «ВМП Казахстан»",
        "projects.p_crane.title": "Демонтаж башенного крана",
        "projects.p_crane.label": "Объект",
        "projects.p_crane.value": "ЖК «Триумф Астаны»",
        "projects.p_velo.title": "Монтаж металлоконструкций на СК «Велотрек»",
        "projects.p_velo.label": "Локация",
        "projects.p_velo.value": "г. Нур-Султан",
        "projects.filter.all": "Все",
        "projects.button": "Смотреть все проекты",

        "partners.title": "Партнёры и заказчики",
        "partners.desc": "Сотрудничаем с ведущими компаниями и выполняем сложные инженерные проекты по всему Казахстану.",
        "partners.subtitle1": "Партнёры",
        "partners.subtitle2": "Постоянные заказчики",
        "partners.c1": "Национальный ЖД оператор РК",
        "partners.c2": "Медицинские страховые организации РК",
        "partners.c3": "Акимат города Нур-Султан",

        "licenses.title": "Лицензии и документы",
        "licenses.text": "Компания имеет лицензию на строительно-монтажные работы 1 категории и приложения к лицензии (перечень работ).",
        "licenses.button": "Смотреть документы",

        "cta.title": "Начните сотрудничество",
        "cta.text": "Опишите задачу и сроки, и мы свяжемся с вами для уточнения деталей и подготовки предложения.",
        "cta.button": "Запросить коммерческое предложение",
        "cta.button.mobile": "Запросить предложение",

        "footer.desc": "RBI Engineering Group работает в Казахстане и выполняет строительство, СМР и модульные решения.",
        "footer.policy": "Политика конфиденциальности",
        "footer.address": "г. Астана, ул. Проезд 69, зд. 1А",
        "footer.rights": "Все права защищены.",

        "services.title": "НАШИ УСЛУГИ",
        "services.subtitle": "Мы выполняем строительные и инженерные работы, а также строим модульные сооружения под разные задачи.",
        "services.button": "ЗАПРОСИТЬ РАСЧЁТ СТОИМОСТИ",
        "services.card.modular.title": "МОДУЛЬНЫЕ СООРУЖЕНИЯ",
        "services.card.modular.d.1": "Сборно-разборные конструкции",
        "services.card.modular.d.2": "Полная внутренняя отделка и коммуникации",
        "services.card.modular.d.3": "Адаптация под климатические условия",
        "services.card.modular.d.4": "Дополнительная кровля, крыльцо и лестницы",
        "services.card.modular.d.5": "Инженерные системы: отопление, вентиляция, электрика",
        "services.card.construction.title": "СТРОИТЕЛЬНО-МОНТАЖНЫЕ РАБОТЫ",
        "services.card.construction.d.1": "Монтаж каркасов зданий и сооружений",
        "services.card.construction.d.2": "Устройство фундаментов любой сложности",
        "services.card.construction.d.3": "Кровельные и фасадные работы",
        "services.card.construction.d.4": "Монтаж сэндвич-панелей",
        "services.card.networks.title": "ИНЖЕНЕРНЫЕ СЕТИ",
        "services.card.networks.d.1": "Прокладка сетей водоснабжения и канализации",
        "services.card.networks.d.2": "Монтаж систем отопления и теплоснабжения",
        "services.card.networks.d.3": "Электромонтажные работы",
        "services.card.finishing.title": "ОТДЕЛОЧНЫЕ РАБОТЫ",
        "services.card.finishing.d.1": "Внутренняя отделка помещений",
        "services.card.finishing.d.2": "Фасадные решения",
        "services.card.finishing.d.3": "Укладка напольных покрытий",
        "services.card.planning.title": "ПРОЕКТИРОВАНИЕ И ПЛАНИРОВАНИЕ",
        "services.card.planning.d.1": "Разработка эскизных и рабочих проектов",
        "services.card.planning.d.2": "Генеральное планирование территории",
        "services.card.planning.d.3": "Авторский надзор",
        "services.card.mounting.title": "МОНТАЖ / ДЕМОНТАЖ",
        "services.card.mounting.d.1": "Монтаж технологического оборудования",
        "services.card.mounting.d.2": "Демонтаж зданий и сооружений",
        "services.card.mounting.d.3": "Передислокация объектов",

        "modular_page.title": "МОДУЛЬНЫЕ СООРУЖЕНИЯ",
        "modular_page.subtitle": "Это быстрый способ построить нужное помещение: офис, КПП, медпункт и другие форматы.",
        "modular_page.button": "РАССЧИТАТЬ СТОИМОСТИ МОДУЛЯ",
        "modular_page.advantages.title": "ПРЕИМУЩЕСТВА",
        "modular_page.advantages.1": "Быстрое строительство",
        "modular_page.advantages.2": "Меньше затрат",
        "modular_page.advantages.3": "Огнестойкость",
        "modular_page.advantages.4": "Долговечность и простота сборки",
        "modular_page.advantages.5": "Энергоэффективность",
        "modular_page.advantages.6": "Возможность строительства в удалённых локациях",
        "modular_page.structure.title": "КОНСТРУКЦИЯ И КОМПЛЕКТАЦИЯ",
        "modular_page.structure.col1.title": "КОНСТРУКЦИЯ МОДУЛЯ",
        "modular_page.structure.col1.1": "Профлист",
        "modular_page.structure.col1.2": "Сэндвич-панели",
        "modular_page.structure.col1.3": "Рамы и утепление",
        "modular_page.structure.col1.4": "Плиты, ЛДСП, линолеум",
        "modular_page.structure.col2.title": "КОМПЛЕКТАЦИЯ",
        "modular_page.structure.col2.1": "Кровля",
        "modular_page.structure.col2.2": "Крыльцо и лестница",
        "modular_page.structure.col2.3": "Металлоконструкции",
        "modular_page.structure.col2.4": "Инженерные сети",
        "modular_page.design.title": "ДИЗАЙН",
        "modular_page.design.panels": "Типы панелей:",
        "modular_page.design.panels.val": "гладкая / волна / трапеция",
        "modular_page.design.colors": "Цвета:",
        "modular_page.design.colors.val": "RAL 9003 (белый), другие цвета по RAL-карте, возможна отделка «под дерево»",
        "modular_page.design.frame": "Каркас:",
        "modular_page.design.frame.val": "RAL 7004 (серый) или другие варианты",
        "modular_page.specs.title": "УСТРОЙСТВО МОДУЛЯ",
        "modular_page.specs.col3.title": "ДИЗАЙН",
        "modular_page.specs.col4.title": "ПРИМЕНЕНИЕ",

        "licenses_page.title": "ЛИЦЕНЗИИ И ДОКУМЕНТЫ",
        "licenses_page.doc.title": "ГОСУДАРСТВЕННАЯ ЛИЦЕНЗИЯ НА СТРОИТЕЛЬНО-МОНТАЖНЫЕ РАБОТЫ (I КАТЕГОРИЯ)",
        "licenses_page.doc.link": "Открыть PDF →",

        "about_page.title": "О КОМПАНИИ",
        "about_page.subtitle": "RBI Engineering Group работает в Казахстане и выполняет строительство, СМР и модульные решения.",
        "about_page.team.title": "КОМАНДА",
        "about_page.team.desc": "50+ сотрудников, регулярная аттестация и повышение квалификации.",
        "about_page.button": "ПОСМОТРЕТЬ ЛИЦЕНЗИИ И ДОКУМЕНТЫ",

        "contacts_page.title": "КОНТАКТЫ",
        "contacts_page.intro": "Мы всегда открыты для новых проектов и партнерства. Оставьте заявку или свяжитесь с нами напрямую, и наши инженеры предложат оптимальное решение для вашей задачи.",
        "contacts_page.address.label": "Адрес:",
        "contacts_page.address.val": "Казахстан, г. Астана, ул. Проезд 69, зд. 1А",
        "contacts_page.phone.label": "Телефон:",
        "contacts_page.form.title": "НАПИШИТЕ НАМ",
        "contacts_page.form.desc": "Напишите, что вам нужно: модуль, монтаж, сети или отделка. Мы ответим и подскажем решение.",
        "contacts_page.form.purpose.label": "Что вас интересует?",
        "contacts_page.form.purpose.placeholder": "Выберите вариант",
        "contacts_page.form.name.label": "Имя / Компания",
        "contacts_page.form.name.placeholder": "Введите имя или название компании",
        "contacts_page.form.phone.placeholder": "Телефон",
        "contacts_page.form.phone.optional": "(Необязательное поле)",
        "contacts_page.form.message.label": "Сообщение",
        "contacts_page.form.message.placeholder": "Опишите ваш запрос",
        "contacts_page.form.submit.email": "ОТПРАВИТЬ НА ПОЧТУ",
        "contacts_page.form.submit.whatsapp": "ОТПРАВИТЬ В WHATSAPP",
        "contacts_page.form.email.required": "(Обязателен при отправке запроса по почте)",
        "contacts_page.form.sending": "Отправка...",
        "contacts_page.form.success": "Запрос успешно отправлен! Мы свяжемся с вами.",
        "contacts_page.form.error": "Произошла ошибка. Пожалуйста, попробуйте еще раз.",
        "contacts_page.form.consent": "Нажимая «Отправить запрос», вы соглашаетесь на обработку персональных данных в соответствии с",

        "policy.title": "Политика конфиденциальности",
        "policy.subtitle": "Настоящая политика конфиденциальности определяет порядок обработки и защиты персональных данных пользователей сайта RBI Engineering Group.",
        "policy.1.title": "1. Оператор персональных данных",
        "policy.1.text": "Оператором персональных данных является\nТоварищество с ограниченной ответственностью «RBI Engineering Group»,\nБИН: [вставь БИН из лицензии],\nРеспублика Казахстан.",
        "policy.2.title": "2. Какие персональные данные собираются",
        "policy.2.text": "При использовании форм обратной связи на сайте компания может собирать следующие персональные данные:",
        "policy.2.l1": "имя;",
        "policy.2.l2": "номер телефона;",
        "policy.2.l3": "адрес электронной почты;",
        "policy.2.l4": "информация, указанная пользователем в тексте обращения.",
        "policy.3.title": "3. Цели обработки персональных данных",
        "policy.3.text": "Персональные данные используются исключительно для:",
        "policy.3.l1": "обработки входящих запросов;",
        "policy.3.l2": "обратной связи с пользователем;",
        "policy.3.l3": "предоставления информации о услугах компании.",
        "policy.4.title": "4. Передача персональных данных третьим лицам",
        "policy.4.text": "Персональные данные пользователей не передаются третьим лицам, за исключением случаев, предусмотренных законодательством Республики Казахстан.",
        "policy.5.title": "5. Хранение и защита персональных данных",
        "policy.5.text": "Персональные данные хранятся в течение времени, необходимого для обработки запроса. Компания принимает необходимые организационные и технические меры для защиты персональных данных от несанкционированного доступа, утраты или раскрытия.",
        "policy.6.title": "6. Контактная информация",
        "policy.6.text": "По вопросам, связанным с обработкой персональных данных, вы можете обратиться через форму обратной связи на сайте или по контактным данным, указанным в разделе ",
        "policy.6.link": "«Контакты»",
    },
    en: {
        "nav.home": "Home",
        "nav.services": "Services",
        "nav.modular": "Modular",
        "nav.projects": "Projects",
        "nav.about": "About",
        "nav.licenses": "Licenses",
        "nav.contacts": "Contacts",
        "nav.consultation": "Get Consultation",
        "button.back": "Back",
        "hero.subtitle": "Astana · Kazakhstan",
        "hero.description": "Modular and construction projects in Kazakhstan. Execution of complex tasks with engineering precision and quality standards.",
        "hero.request": "Request a Proposal",
        "hero.projects": "View Projects",
        "hero.trust.years": "13+ years of experience",
        "hero.trust.projects": "60+ projects",
        "hero.trust.license": "Category 1 License",

        "about.title": "Company Profile",
        "about.desc": "RBI Engineering Group is a full-cycle construction organization specializing in complex construction and installation works and the design of high-tech modular structures.",
        "about.subdesc": "We implement industrial and infrastructure projects throughout Kazakhstan, ensuring a high culture of engineering and compliance with strict technological standards.",
        "about.stat.years": "YEARS ON MARKET",
        "about.stat.projects": "COMPLETED PROJECTS",
        "about.stat.employees": "EMPLOYEES",
        "about.stat.machinery": "UNITS OF MACHINERY",
        "about.stat.license": "CONSTRUCTION LICENSE",
        "about.stat.license.suffix": " CAT.",

        "activities.eyebrow": "Services",
        "activities.title": "Comprehensive Engineering Solutions",
        "activities.desc": "We ensure impeccable execution quality at every stage of the project.",
        "activities.modular.title": "Modular Structures",
        "activities.modular.desc": "Rapid construction of high-tech turnkey facilities.",
        "activities.construction.title": "Construction Works",
        "activities.construction.desc": "Professional implementation of large-scale infrastructure and industrial projects.",
        "activities.networks.title": "Engineering Networks",
        "activities.networks.desc": "Design and installation of complex internal and external communication systems.",
        "activities.finishing.title": "Finishing Works",
        "activities.finishing.desc": "Premium-level finishing using wear-resistant materials.",
        "activities.planning.title": "Design and Planning",
        "activities.planning.desc": "Development of high-precision design documentation and general planning.",
        "activities.mounting.title": "Installation and Dismantling Works",
        "activities.mounting.desc": "Complex installation of technological equipment and metal structures of any scale.",
        "activities.button": "All Services",

        "modular.title": "Modular Structures",
        "modular.text": "Modular structures are a fast and practical way to get a ready-made facility. Suitable for remote locations and various types of objects.",
        "modular.subtitle": "Why is it profitable?",
        "modular.detail": "Time and budget savings: buildings are assembled locally directly on site. Full factory readiness, including finishing and engineering systems.",
        "modular.benefit1.title": "Fast",
        "modular.benefit1.desc": "Assembly in a few days",
        "modular.benefit2.title": "Reliable",
        "modular.benefit2.desc": "Works in any weather conditions",
        "modular.benefit3.title": "Mobile",
        "modular.benefit3.desc": "Easy to transport to a new location",
        "modular.button": "Learn more",

        "competencies.eyebrow": "Why Us",
        "competencies.title": "Key Competencies",
        "competencies.title_alt": "Why Choose Us",
        "competencies.c1.title": "Experience and Scale",
        "competencies.c1.desc": "13+ years on the Kazakhstan market, 60+ completed projects.",
        "competencies.c2.title": "Professional Team",
        "competencies.c2.desc": "50+ employees, regular certification and advanced training.",
        "competencies.c3.title": "Technical Capabilities",
        "competencies.c3.desc": "Own fleet of 53+ units of construction machinery and service department.",
        "competencies.c4.title": "Specialization in Modules",
        "competencies.c4.desc": "We know the features of modular structures and configurations.",
        "competencies.c5.title": "Partner Network",
        "competencies.c5.desc": "Cooperation with major manufacturers and companies (DoorHan, Power China, etc.).",
        "competencies.c6.title": "Documents and Confirmations",
        "competencies.c6.desc": "Category 1 license and 68+ letters of recommendation.",

        "where.title": "Areas of Application",
        "where.i1": "Security Posts / Checkpoints",
        "where.i2": "Control Rooms and Technical Premises",
        "where.i3": "Factories",
        "where.i4": "Wind Power Plants",
        "where.i5": "Mobile Offices and Schools",
        "where.i6": "Military Construction",
        "where.i7": "Residential and Medical Facilities",

        "projects.title": "Projects",
        "projects.desc": "Examples of completed works on modular solutions and installation projects.",
        "projects.cat.modular": "Modular Structures",
        "projects.cat.metal": "Installation / Metal Structures",
        "projects.p1.title": "Khromtau WPP",
        "projects.p1.label": "Partners",
        "projects.p2.title": "Wind Turbine Installation",
        "projects.p2.label": "Location",
        "projects.p2.value": "Petropavlovsk",
        "projects.p3.title": "Canteen for Military Base",
        "projects.p3.label": "Client",
        "projects.p3.value": "JSC \"Askeri Kurylys\"",
        "projects.p4.title": "Installation of Khan Shatyr structures",
        "projects.p4.label": "Object",
        "projects.p4.value": "Khan Shatyr",
        "projects.p5.title": "Construction Headquarters",
        "projects.p5.label": "Area",
        "projects.p5.value": "850 m²",
        "projects.p6.title": "Shift Camp",
        "projects.p6.label": "Capacity",
        "projects.p6.value": "300 people",
        "projects.p_conf.title": "Conference Hall (Almaty)",
        "projects.p_conf.label": "Location",
        "projects.p_conf.value": "Almaty",
        "projects.p_lab.title": "PCR Laboratory (Aksai)",
        "projects.p_lab.label": "Location",
        "projects.p_lab.value": "Aksai",
        "projects.p_pavilion.title": "Bus Stop Pavilion",
        "projects.p_pavilion.label": "Client",
        "projects.p_pavilion.value": "City Akimat",
        "projects.p_terminal.title": "Customs Terminal",
        "projects.p_terminal.label": "Type",
        "projects.p_terminal.value": "Infrastructure Object",
        "projects.p_factory.title": "Factories and Warehouses",
        "projects.p_factory.label": "Client",
        "projects.p_factory.value": "VMP Kazakhstan LLP",
        "projects.p_crane.title": "Dismantling of Tower Crane",
        "projects.p_crane.label": "Object",
        "projects.p_crane.value": "Astana Triumph RC",
        "projects.p_velo.title": "Installation of metal structures at Saryarka Velodrome",
        "projects.p_velo.label": "Location",
        "projects.p_velo.value": "Nur-Sultan",
        "projects.filter.all": "All",
        "projects.button": "View All Projects",

        "partners.title": "Partners and Clients",
        "partners.desc": "We cooperate with leading companies and perform complex engineering projects throughout Kazakhstan.",
        "partners.subtitle1": "Partners",
        "partners.subtitle2": "Regular Clients",
        "partners.c1": "National Railway Operator of Kazakhstan",
        "partners.c2": "Medical Insurance Organizations of Kazakhstan",
        "partners.c3": "Akimat of Nur-Sultan City",

        "licenses.title": "Licenses and Documents",
        "licenses.text": "The company has a license for construction and installation works of the 1st category and appendices to the license (list of works).",
        "licenses.button": "View Documents",

        "cta.title": "Start Cooperation",
        "cta.text": "Describe the task and deadlines, and we will contact you to clarify details and prepare a proposal.",
        "cta.button": "Request a Commercial Proposal",
        "cta.button.mobile": "Request Proposal",

        "footer.desc": "RBI Engineering Group operates in Kazakhstan and performs construction, installation works, and modular solutions.",
        "footer.policy": "Privacy Policy",
        "footer.address": "Astana, Proyezd 69 st., bldg. 1A",
        "footer.rights": "All rights reserved.",

        "services.title": "OUR SERVICES",
        "services.subtitle": "We perform construction and engineering works and build modular structures for various purposes.",
        "services.button": "REQUEST A COST ESTIMATE",
        "services.card.modular.title": "MODULAR STRUCTURES",
        "services.card.modular.d.1": "Collapsible structures",
        "services.card.modular.d.2": "Complete internal finishing and communications",
        "services.card.modular.d.3": "Adaptation to climatic conditions",
        "services.card.modular.d.4": "Additional roofing, porch and stairs",
        "services.card.modular.d.5": "Engineering systems: heating, ventilation, electrics",
        "services.card.construction.title": "CONSTRUCTION AND INSTALLATION WORKS",
        "services.card.construction.d.1": "Installation of building and structure frames",
        "services.card.construction.d.2": "Construction of foundations of any complexity",
        "services.card.construction.d.3": "Roofing and facade works",
        "services.card.construction.d.4": "Installation of sandwich panels",
        "services.card.networks.title": "ENGINEERING NETWORKS",
        "services.card.networks.d.1": "Laying of water supply and sewage networks",
        "services.card.networks.d.2": "Installation of heating and heat supply systems",
        "services.card.networks.d.3": "Electrical installation works",
        "services.card.finishing.title": "FINISHING WORKS",
        "services.card.finishing.d.1": "Interior finishing of premises",
        "services.card.finishing.d.2": "Facade solutions",
        "services.card.finishing.d.3": "Flooring installation",
        "services.card.planning.title": "DESIGN AND PLANNING",
        "services.card.planning.d.1": "Development of draft and working projects",
        "services.card.planning.d.2": "General territory planning",
        "services.card.planning.d.3": "Author's supervision",
        "services.card.mounting.title": "INSTALLATION AND DISMANTLING WORKS",
        "services.card.mounting.d.1": "Installation of technological equipment",
        "services.card.mounting.d.2": "Dismantling of buildings and structures",
        "services.card.mounting.d.3": "Relocation of objects",

        "modular_page.title": "MODULAR STRUCTURES",
        "modular_page.subtitle": "This is a fast way to build the required facility: offices, checkpoints, medical units, and other formats.",
        "modular_page.button": "CALCULATE MODULE COST",
        "modular_page.advantages.title": "ADVANTAGES",
        "modular_page.advantages.1": "Fast construction",
        "modular_page.advantages.2": "Lower costs",
        "modular_page.advantages.3": "Fire resistance",
        "modular_page.advantages.4": "Durability and ease of assembly",
        "modular_page.advantages.5": "Energy efficiency",
        "modular_page.advantages.6": "Suitable for construction in remote locations",
        "modular_page.structure.title": "STRUCTURE AND EQUIPMENT",
        "modular_page.structure.col1.title": "MODULE STRUCTURE",
        "modular_page.structure.col1.1": "Profiled sheet",
        "modular_page.structure.col1.2": "Sandwich panels",
        "modular_page.structure.col1.3": "Frame and insulation",
        "modular_page.structure.col1.4": "Panels, laminated boards, linoleum",
        "modular_page.structure.col2.title": "EQUIPMENT",
        "modular_page.structure.col2.1": "Roofing",
        "modular_page.structure.col2.2": "Porch and stairs",
        "modular_page.structure.col2.3": "Metal structures",
        "modular_page.structure.col2.4": "Engineering networks",
        "modular_page.design.title": "DESIGN",
        "modular_page.design.panels": "Panel types:",
        "modular_page.design.panels.val": "smooth / wave / trapeze",
        "modular_page.design.colors": "Colors:",
        "modular_page.design.colors.val": "RAL 9003 (white), other colors by RAL card, wood-like finish available",
        "modular_page.design.frame": "Frame:",
        "modular_page.design.frame.val": "RAL 7004 (grey) or other options",
        "modular_page.specs.title": "MODULE SPECIFICATIONS",
        "modular_page.specs.col3.title": "DESIGN",
        "modular_page.specs.col4.title": "APPLICATION",

        "licenses_page.title": "LICENSES AND DOCUMENTS",
        "licenses_page.doc.title": "STATE LICENSE FOR CONSTRUCTION AND INSTALLATION WORKS (CATEGORY I)",
        "licenses_page.doc.link": "Open PDF →",

        "about_page.title": "ABOUT THE COMPANY",
        "about_page.subtitle": "RBI Engineering Group operates in Kazakhstan and performs construction, installation works, and modular solutions.",
        "about_page.team.title": "TEAM",
        "about_page.team.desc": "50+ employees, regular certification and advanced training.",
        "about_page.button": "VIEW LICENSES AND DOCUMENTS",

        "contacts_page.title": "CONTACTS",
        "contacts_page.intro": "We are always open to new projects and partnerships. Leave a request or contact us directly, and our engineers will propose the optimal solution for your task.",
        "contacts_page.address.label": "Address:",
        "contacts_page.address.val": "Kazakhstan, Astana, Proezd 69 st., bldg. 1A",
        "contacts_page.phone.label": "Phone:",
        "contacts_page.form.title": "WRITE TO US",
        "contacts_page.form.desc": "Tell us what you need: modules, installation, engineering networks, or finishing works. We will contact you and propose a solution.",
        "contacts_page.form.purpose.label": "What are you interested in?",
        "contacts_page.form.purpose.placeholder": "Select an option",
        "contacts_page.form.name.label": "Name / Company",
        "contacts_page.form.name.placeholder": "Enter name or company name",
        "contacts_page.form.phone.placeholder": "Phone",
        "contacts_page.form.phone.optional": "(Optional field)",
        "contacts_page.form.message.label": "Message",
        "contacts_page.form.message.placeholder": "Describe your request",
        "contacts_page.form.submit.email": "SEND VIA EMAIL",
        "contacts_page.form.submit.whatsapp": "SEND VIA WHATSAPP",
        "contacts_page.form.email.required": "(required only when sending via email)",
        "contacts_page.form.sending": "Sending...",
        "contacts_page.form.success": "Request sent successfully! We will contact you.",
        "contacts_page.form.error": "An error occurred. Please try again.",
        "contacts_page.form.consent": "By clicking “Send request”, you agree to the processing of personal data in accordance with the",

        "policy.title": "PRIVACY POLICY",
        "policy.subtitle": "This Privacy Policy defines the procedure for processing and protecting the personal data of users of the RBI Engineering Group website.",
        "policy.1.title": "1. PERSONAL DATA CONTROLLER",
        "policy.1.text": "The personal data controller is\nRBI Engineering Group LLP,\nBIN: [insert BIN from license],\nRepublic of Kazakhstan.",
        "policy.2.title": "2. WHAT PERSONAL DATA IS COLLECTED",
        "policy.2.text": "When using the feedback forms on the website, the company may collect the following personal data:",
        "policy.2.l1": "name;",
        "policy.2.l2": "phone number;",
        "policy.2.l3": "email address;",
        "policy.2.l4": "information provided by the user in the message text.",
        "policy.3.title": "3. PURPOSES OF PERSONAL DATA PROCESSING",
        "policy.3.text": "Personal data is used exclusively for:",
        "policy.3.l1": "processing incoming requests;",
        "policy.3.l2": "contacting the user;",
        "policy.3.l3": "providing information about the company’s services.",
        "policy.4.title": "4. TRANSFER OF PERSONAL DATA TO THIRD PARTIES",
        "policy.4.text": "Users’ personal data is not transferred to third parties, except in cases provided for by the legislation of the Republic of Kazakhstan.",
        "policy.5.title": "5. STORAGE AND PROTECTION OF PERSONAL DATA",
        "policy.5.text": "Personal data is stored for the period necessary to process the request. The company takes the necessary organizational and technical measures to protect personal data from unauthorized access, loss, or disclosure.",
        "policy.6.title": "6. CONTACT INFORMATION",
        "policy.6.text": "For questions related to the processing of personal data, you may contact us via the feedback form on the website or using the contact details provided in the ",
        "policy.6.link": "“Contacts” section",
    }
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>('ru');

    // Load saved language from localStorage if available
    useEffect(() => {
        const savedLang = localStorage.getItem('language') as Language;
        if (savedLang && (savedLang === 'ru' || savedLang === 'en')) {
            setLanguage(savedLang);
        }
    }, []);

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
